# Streamlit Cloud Secrets Configuration
# This file is for local development
# For production, set these in Streamlit Cloud dashboard

OPENAI_API_KEY = "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"
OPENROUTER_API_KEY = "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"

# Optional: Email configuration
# SMTP_SERVER = "smtp.gmail.com"
# SMTP_PORT = 587
# EMAIL_USERNAME = "your-email@gmail.com"
# EMAIL_PASSWORD = "your-app-password"
