# Local development secrets template
# Copy this file to .streamlit/secrets.toml and add your actual API key
OPENROUTER_API_KEY = "YOUR_ACTUAL_API_KEY_HERE"
APP_REFERRER = "https://smart-receivables-glove.streamlit.app"
APP_TITLE = "Smart Receivables"
